### PR TITLE
Major patch 4

### PR DESCRIPTION
**Pull request by ShroomAgent27**
* Update Thermal Foundation series
* Update Industrial Foregoing
* Add FTBChunks

This PR will be ready for review when [Thermal Dynamics](https://www.curseforge.com/minecraft/mc-mods/thermal-dynamics/files/all) updates

### CODE REVIEW

**Comment by tanyan-tanyan** [comment]
Add Metal Barrels too
https://www.curseforge.com/minecraft/mc-mods/metal-barrels

**Comment by ShroomAgent27** [comment]
See, the surprise is that Thermal Dynamics will never update. Thus, the patch will never happen! Mwhahahaha!

**Review by tanyan-tanyan — DISMISSED** [review]

**Comment by tanyan-tanyan** [comment]
Don't forget to review the new mods in dev channel and update mekanism configs

**Comment by ShroomAgent27** [comment]
## Mods Added
* Architectury API
* Clumps
* Cosmetic Armor Reworked
* ConnectedTexturesMod
* FTB Chunks
* FTB GUI Library
* Immersive Posts
* Metal Barrels
* Thermal Innovation
* YUNG's API

## Mods Updated
* Applied Energistics 2
* Ars Nouveau
* YUNG's Better Caves
* Biomes O' Plenty
* Blood Magic
* Botania
* Oh The Biomes You'll Go
* CodeChicken Lib
* CoFH Core
* CraftTweaker
* Curios API
* Cyclic
* Decorative Blocks
* Dungeons Plus
* Ender Storage
* End Remastered
* Engineer's Decor
* FTB Ultimine
* GeckoLib
* Global XP
* GraveStone Mod
* Immersive Engineering
* Immersive Posts
* Just Enough Items (JEI)
* Just Enough Resources (JER)
* Mantle
* Macaw's Bridges
* Macaw's Doors
* Macaw's Furniture
* Macaw's Roofs
* Macaw's Trapdoors
* Mekanism
* Mekanism Generators
* Mekanism Tools
* More Red
* Moving Elevators
* Nature's Aura
* Nature's Compass
* ObserverLib
* Pam's HarvestCraft 2 - Food Core
* Pam's HarvestCraft 2 - Food Extended
* Placebo
* PneumaticCraft: Repressurized
* Polymorph
* Quark
* Refined Storage
* Storage Drawers
* Structure Gel API
* Supplementaries
* The One Probe
* Thermal Foundation
* Thermal Expansion
* Titanium
* Trash Cans
* VanillaTweaks
* Xaero's Minimap
* Xaero's World Map

## Mods Removed
* Double Slabs (Already removed tho lol)
* Health Scoring
* Just Enough Calculation (JEC)

**Review by tanyan-tanyan — APPROVED** [review]

**Pull request closed without merging**
